CREATE TABLE IF NOT EXISTS `trade_orders` (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_order_id BIGINT,
    account_id BIGINT NOT NULL,
    isin VARCHAR(255) NOT NULL,
    side VARCHAR(50),
    trade_currency VARCHAR(10),
    quantity INTEGER NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    order_type VARCHAR(50),
    limit_price NUMERIC(19, 4), -- Precision can be adjusted
    status VARCHAR(50),
    registration_time TIMESTAMP WITH TIME ZONE,
    executed_time TIMESTAMP WITH TIME ZONE,
    execution_price NUMERIC(19, 4),

    created_by VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP WITH TIME ZONE
);